const columns = [
  "Name",
  "Date of Birth",
  "Email",
  "Phone",
  "Address",
  "Status In Canada",
  "Arrival Date",
  "Height",
  "Weight",
  "Years In Canada",
  "Birth Country",
  "Marital Status",
  "Work Status",
  "Occupation",
  "Employer Name",
  "Employer Address",
  "Annual Income",
  "Smoking Status",
  "Drinking Status",
  "Family Doctor",
  "Clinic Address",
  "Doctor's Last Visit",
  "Any Family History",
  "Any Health Issues",
  "Dangerous Sports",
  "Replacing Old Policy",
  "Any Licence Suspension",
  "Face Amount",
  "Beneficiary 1",
  "Beneficiary 2",
  "Assets",
  "Liabilities",
  "Bank Number",
  "Transit Number",
  "Account Number",
  "Signature",
  "Created At",
];

export default columns;
