const columns = [
  "Name",
  "Date of Birth",
  "Email",
  "Phone",
  "Address",
  "City",
  "Street No",
  "Suite No",
  "Postal Code",
  "Status In Canada",
  "Arrival Date",
  "Years In Canada",
  "Birth Country",
  "Height",
  "Weight",
  "Marital Status",
  "No of Children",
  "No of Male Children",
  "No of Female Children",
  "No of Infants",
  "Work Status",
  "Occupation",
  "Employer Name",
  "Employer Address",
  "Employer City",
  "Employer Street No",
  "Employer Suite No",
  "Employer Postal Code",
  "Annual Income",
  "Smoking Status",
  "Drinking Status",
  "Family Doctor",
  "Clinic Address",
  "Clinic City",
  "Clinic Street No",
  "Clinic Suite No",
  "Clinic Postal Code",
  "Doctor's Last Visit",
  "Any Family History",
  "Any Health Issues",
  "Dangerous Sports",
  "Replacing Old Policy",
  "Any Licence Suspension",
  "Face Amount",
  "Beneficiary 1",
  "Beneficiary 2",
  "Assets",
  "Liabilities",
  "Bank Number",
  "Transit Number",
  "Account Number",
  "Signature",
  "Created At",
];

export default columns;
